### ISSUE TITLE
sv_ttk lib missing in executable

### ISSUE THREAD

**Issue by ThePromidius** [MangaManagerORG/FMD3#8]
```log
Traceback (most recent call last):
  File "FMD3_Tkinter\__main__.py", line 18, in <module>
    main()
  File "FMD3_Tkinter\__main__.py", line 15, in main
    run_local()
  File "FMD3_Tkinter\run_local.py", line 8, in run_local
    from FMD3_Tkinter.app import app
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "FMD3_Tkinter\app\__init__.py", line 396, in <module>
    app = TkinterUI()
          ^^^^^^^^^^^
  File "FMD3_Tkinter\app\__init__.py", line 183, in __init__
    sv_ttk.set_theme("dark")
  File "sv_ttk\__init__.py", line 30, in set_theme
  File "sv_ttk\__init__.py", line 16, in _load_theme
_tkinter.TclError: couldn't read file "C:\Users\galla\AppData\Local\Temp\_MEI130162\sv_ttk\sv.tcl": no such file or directory```

**Comment by ThePromidius** [comment]
sv_ttk will no longer be used
